-- phpMyAdmin SQL Dump
-- version 4.6.5.2
-- https://www.phpmyadmin.net/
--
-- Máy chủ: 127.0.0.1
-- Thời gian đã tạo: Th10 02, 2017 lúc 10:58 SA
-- Phiên bản máy phục vụ: 10.1.21-MariaDB
-- Phiên bản PHP: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Cơ sở dữ liệu: `project_jatovi`
--

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `tb_tintuc`
--

CREATE TABLE `tb_tintuc` (
  `id_tintuc` int(11) NOT NULL,
  `tieude` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
  `hinhanh` varchar(250) COLLATE utf8_unicode_ci NOT NULL,
  `noidung` text COLLATE utf8_unicode_ci NOT NULL,
  `ngaydang` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tacgia` varchar(150) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Đang đổ dữ liệu cho bảng `tb_tintuc`
--

INSERT INTO `tb_tintuc` (`id_tintuc`, `tieude`, `hinhanh`, `noidung`, `ngaydang`, `tacgia`) VALUES
(48, 'Kem dưỡng chất collagen trắng da', 'MoistOne1.jpg', '<p><strong>L&agrave;n da rất nhạy cảm với c&aacute;c t&aacute;c động m&ocirc;i trường v&agrave; nhanh ch&oacute;ng &ldquo; xuống cấp&rdquo; nếu kh&ocirc;ng được chăm s&oacute;c cẩn thận.&nbsp;Da th&ocirc; r&aacute;p, nhăn nheo, thiếu sức sống l&agrave; những dấu hiệu l&atilde;o h&oacute;a v&agrave; cũng ch&iacute;nh l&agrave; nỗi &aacute;m ảnh của mọi chị em phụ nữ.</strong></p>\r\n\r\n<p>Ng&agrave;y đăng: 1-11-2017</p>\r\n\r\n<p>576 lượt xem</p>\r\n\r\n<p>Với mong muốn t&igrave;m lại vẻ đẹp đ&ocirc;i mươi, kh&ocirc;ng &iacute;t c&aacute;c chị em đ&atilde; dốc hầu bao đổ v&agrave;o c&aacute;c Spa, thẩm mỹ viện, tiến h&agrave;nh phẫu thuật. Mặc d&ugrave; tốn k&eacute;m v&agrave; mất nhiều thời gian, nhưng chưa chắc đ&atilde; mang lại hiệu quả như &yacute;, thậm tr&iacute; còn làm cho da xấu, gi&agrave; đi trước tuổi.<br />\r\n&nbsp;</p>\r\n\r\n<p>Collagen l&agrave; một loại protein, chiếm 25% tổng lượng protein trong cơ thể, c&oacute; chức năng li&ecirc;n kết c&aacute;c m&ocirc;. Với tổ chức da, b&ecirc;n cạnh nhiệm vụ li&ecirc;n kết, Collagen c&ograve;n c&oacute; chức năng tạo n&ecirc;n sự đ&agrave;n hồi, gi&uacute;p da duy tr&igrave; độ ẩm, tăng khả năng giữ nước để da lu&ocirc;n căng mịn. V&igrave; thế khi collagen bị mất đi do qu&aacute; tr&igrave;nh l&atilde;o ho&aacute; của cơ thể da sẽ bị tr&ugrave;ng nh&atilde;o, nhiều nếp nhăn.Theo quy luật tự nhi&ecirc;n, trung b&igrave;nh một người sẽ mất khoảng 30% tổng lượng collagen khi chạm ngưỡng 40 tuổi.<br />\r\n&nbsp;</p>\r\n\r\n<p>Do đ&oacute;, c&aacute;ch đơn giản v&agrave; kinh tế nhất để giữ m&atilde;i tuổi thanh xu&acirc;n là &nbsp;l&agrave; sử dụng sản ph&acirc;̉m kem dưỡng ch&acirc;́t collagen trắng da Moistone Ostrich Collagen Gel Cung cấp đầy đủ c&aacute;c dưỡng chất cần thiết cho da, gi&uacute;p da giữ ẩm, săn chắc, đ&agrave;n hồi, căng mịn, trắng s&aacute;ng v&agrave; đầy sức sống cũng như l&agrave;m chậm đi qu&aacute; tr&igrave;nh l&atilde;o h&oacute;a da.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Kem dưỡng ch&acirc;́t collagen trắng da Moistone Ostrich Collagen Gel gồm collagen h&ograve;a tan từ đ&agrave; điểu kết hợp với nano collagen từ vi c&aacute; hồng v&agrave; c&aacute;c dưỡng chất qu&yacute; kh&aacute;c được đ&aacute;nh gi&aacute; l&agrave; sản phẩm kem dưỡng da cao cấp tại Nhật Bản, cung cấp đầy đủ c&aacute;c dưỡng chất cần thiết cho da, gi&uacute;p da giữ ẩm, săn chắc, đ&agrave;n hồi, căng mịn, trắng s&aacute;ng v&agrave; đầy sức sống cũng như l&agrave;m chậm đi qu&aacute; tr&igrave;nh l&atilde;o h&oacute;a.</p>\r\n', '2017-11-02 05:12:36', 'Nguyen Anh Tuan'),
(49, 'Kem dưỡng chất collagen trắng da', 'MoistOne1.jpg', '<p><strong>L&agrave;n da rất nhạy cảm với c&aacute;c t&aacute;c động m&ocirc;i trường v&agrave; nhanh ch&oacute;ng &ldquo; xuống cấp&rdquo; nếu kh&ocirc;ng được chăm s&oacute;c cẩn thận.&nbsp;Da th&ocirc; r&aacute;p, nhăn nheo, thiếu sức sống l&agrave; những dấu hiệu l&atilde;o h&oacute;a v&agrave; cũng ch&iacute;nh l&agrave; nỗi &aacute;m ảnh của mọi chị em phụ nữ.</strong></p>\r\n\r\n<p>Ng&agrave;y đăng: 1-11-2017</p>\r\n\r\n<p>576 lượt xem</p>\r\n\r\n<p>Với mong muốn t&igrave;m lại vẻ đẹp đ&ocirc;i mươi, kh&ocirc;ng &iacute;t c&aacute;c chị em đ&atilde; dốc hầu bao đổ v&agrave;o c&aacute;c Spa, thẩm mỹ viện, tiến h&agrave;nh phẫu thuật. Mặc d&ugrave; tốn k&eacute;m v&agrave; mất nhiều thời gian, nhưng chưa chắc đ&atilde; mang lại hiệu quả như &yacute;, thậm tr&iacute; còn làm cho da xấu, gi&agrave; đi trước tuổi.<br />\r\n&nbsp;</p>\r\n\r\n<p>Collagen l&agrave; một loại protein, chiếm 25% tổng lượng protein trong cơ thể, c&oacute; chức năng li&ecirc;n kết c&aacute;c m&ocirc;. Với tổ chức da, b&ecirc;n cạnh nhiệm vụ li&ecirc;n kết, Collagen c&ograve;n c&oacute; chức năng tạo n&ecirc;n sự đ&agrave;n hồi, gi&uacute;p da duy tr&igrave; độ ẩm, tăng khả năng giữ nước để da lu&ocirc;n căng mịn. V&igrave; thế khi collagen bị mất đi do qu&aacute; tr&igrave;nh l&atilde;o ho&aacute; của cơ thể da sẽ bị tr&ugrave;ng nh&atilde;o, nhiều nếp nhăn.Theo quy luật tự nhi&ecirc;n, trung b&igrave;nh một người sẽ mất khoảng 30% tổng lượng collagen khi chạm ngưỡng 40 tuổi.<br />\r\n&nbsp;</p>\r\n\r\n<p>Do đ&oacute;, c&aacute;ch đơn giản v&agrave; kinh tế nhất để giữ m&atilde;i tuổi thanh xu&acirc;n là &nbsp;l&agrave; sử dụng sản ph&acirc;̉m kem dưỡng ch&acirc;́t collagen trắng da Moistone Ostrich Collagen Gel Cung cấp đầy đủ c&aacute;c dưỡng chất cần thiết cho da, gi&uacute;p da giữ ẩm, săn chắc, đ&agrave;n hồi, căng mịn, trắng s&aacute;ng v&agrave; đầy sức sống cũng như l&agrave;m chậm đi qu&aacute; tr&igrave;nh l&atilde;o h&oacute;a da.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Kem dưỡng ch&acirc;́t collagen trắng da Moistone Ostrich Collagen Gel gồm collagen h&ograve;a tan từ đ&agrave; điểu kết hợp với nano collagen từ vi c&aacute; hồng v&agrave; c&aacute;c dưỡng chất qu&yacute; kh&aacute;c được đ&aacute;nh gi&aacute; l&agrave; sản phẩm kem dưỡng da cao cấp tại Nhật Bản, cung cấp đầy đủ c&aacute;c dưỡng chất cần thiết cho da, gi&uacute;p da giữ ẩm, săn chắc, đ&agrave;n hồi, căng mịn, trắng s&aacute;ng v&agrave; đầy sức sống cũng như l&agrave;m chậm đi qu&aacute; tr&igrave;nh l&atilde;o h&oacute;a.</p>\r\n', '2017-11-02 05:12:36', 'Nguyen Anh Tuan'),
(50, 'Kem dưỡng chất collagen trắng da', 'MoistOne1.jpg', '<p><strong>L&agrave;n da rất nhạy cảm với c&aacute;c t&aacute;c động m&ocirc;i trường v&agrave; nhanh ch&oacute;ng &ldquo; xuống cấp&rdquo; nếu kh&ocirc;ng được chăm s&oacute;c cẩn thận.&nbsp;Da th&ocirc; r&aacute;p, nhăn nheo, thiếu sức sống l&agrave; những dấu hiệu l&atilde;o h&oacute;a v&agrave; cũng ch&iacute;nh l&agrave; nỗi &aacute;m ảnh của mọi chị em phụ nữ.</strong></p>\r\n\r\n<p>Ng&agrave;y đăng: 1-11-2017</p>\r\n\r\n<p>576 lượt xem</p>\r\n\r\n<p>Với mong muốn t&igrave;m lại vẻ đẹp đ&ocirc;i mươi, kh&ocirc;ng &iacute;t c&aacute;c chị em đ&atilde; dốc hầu bao đổ v&agrave;o c&aacute;c Spa, thẩm mỹ viện, tiến h&agrave;nh phẫu thuật. Mặc d&ugrave; tốn k&eacute;m v&agrave; mất nhiều thời gian, nhưng chưa chắc đ&atilde; mang lại hiệu quả như &yacute;, thậm tr&iacute; còn làm cho da xấu, gi&agrave; đi trước tuổi.<br />\r\n&nbsp;</p>\r\n\r\n<p>Collagen l&agrave; một loại protein, chiếm 25% tổng lượng protein trong cơ thể, c&oacute; chức năng li&ecirc;n kết c&aacute;c m&ocirc;. Với tổ chức da, b&ecirc;n cạnh nhiệm vụ li&ecirc;n kết, Collagen c&ograve;n c&oacute; chức năng tạo n&ecirc;n sự đ&agrave;n hồi, gi&uacute;p da duy tr&igrave; độ ẩm, tăng khả năng giữ nước để da lu&ocirc;n căng mịn. V&igrave; thế khi collagen bị mất đi do qu&aacute; tr&igrave;nh l&atilde;o ho&aacute; của cơ thể da sẽ bị tr&ugrave;ng nh&atilde;o, nhiều nếp nhăn.Theo quy luật tự nhi&ecirc;n, trung b&igrave;nh một người sẽ mất khoảng 30% tổng lượng collagen khi chạm ngưỡng 40 tuổi.<br />\r\n&nbsp;</p>\r\n\r\n<p>Do đ&oacute;, c&aacute;ch đơn giản v&agrave; kinh tế nhất để giữ m&atilde;i tuổi thanh xu&acirc;n là &nbsp;l&agrave; sử dụng sản ph&acirc;̉m kem dưỡng ch&acirc;́t collagen trắng da Moistone Ostrich Collagen Gel Cung cấp đầy đủ c&aacute;c dưỡng chất cần thiết cho da, gi&uacute;p da giữ ẩm, săn chắc, đ&agrave;n hồi, căng mịn, trắng s&aacute;ng v&agrave; đầy sức sống cũng như l&agrave;m chậm đi qu&aacute; tr&igrave;nh l&atilde;o h&oacute;a da.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Kem dưỡng ch&acirc;́t collagen trắng da Moistone Ostrich Collagen Gel gồm collagen h&ograve;a tan từ đ&agrave; điểu kết hợp với nano collagen từ vi c&aacute; hồng v&agrave; c&aacute;c dưỡng chất qu&yacute; kh&aacute;c được đ&aacute;nh gi&aacute; l&agrave; sản phẩm kem dưỡng da cao cấp tại Nhật Bản, cung cấp đầy đủ c&aacute;c dưỡng chất cần thiết cho da, gi&uacute;p da giữ ẩm, săn chắc, đ&agrave;n hồi, căng mịn, trắng s&aacute;ng v&agrave; đầy sức sống cũng như l&agrave;m chậm đi qu&aacute; tr&igrave;nh l&atilde;o h&oacute;a.</p>\r\n', '2017-11-02 05:12:36', 'Nguyen Anh Tuan'),
(51, 'Kem dưỡng chất collagen trắng da', 'MoistOne1.jpg', '<p><strong>L&agrave;n da rất nhạy cảm với c&aacute;c t&aacute;c động m&ocirc;i trường v&agrave; nhanh ch&oacute;ng &ldquo; xuống cấp&rdquo; nếu kh&ocirc;ng được chăm s&oacute;c cẩn thận.&nbsp;Da th&ocirc; r&aacute;p, nhăn nheo, thiếu sức sống l&agrave; những dấu hiệu l&atilde;o h&oacute;a v&agrave; cũng ch&iacute;nh l&agrave; nỗi &aacute;m ảnh của mọi chị em phụ nữ.</strong></p>\r\n\r\n<p>Ng&agrave;y đăng: 1-11-2017</p>\r\n\r\n<p>576 lượt xem</p>\r\n\r\n<p>Với mong muốn t&igrave;m lại vẻ đẹp đ&ocirc;i mươi, kh&ocirc;ng &iacute;t c&aacute;c chị em đ&atilde; dốc hầu bao đổ v&agrave;o c&aacute;c Spa, thẩm mỹ viện, tiến h&agrave;nh phẫu thuật. Mặc d&ugrave; tốn k&eacute;m v&agrave; mất nhiều thời gian, nhưng chưa chắc đ&atilde; mang lại hiệu quả như &yacute;, thậm tr&iacute; còn làm cho da xấu, gi&agrave; đi trước tuổi.<br />\r\n&nbsp;</p>\r\n\r\n<p>Collagen l&agrave; một loại protein, chiếm 25% tổng lượng protein trong cơ thể, c&oacute; chức năng li&ecirc;n kết c&aacute;c m&ocirc;. Với tổ chức da, b&ecirc;n cạnh nhiệm vụ li&ecirc;n kết, Collagen c&ograve;n c&oacute; chức năng tạo n&ecirc;n sự đ&agrave;n hồi, gi&uacute;p da duy tr&igrave; độ ẩm, tăng khả năng giữ nước để da lu&ocirc;n căng mịn. V&igrave; thế khi collagen bị mất đi do qu&aacute; tr&igrave;nh l&atilde;o ho&aacute; của cơ thể da sẽ bị tr&ugrave;ng nh&atilde;o, nhiều nếp nhăn.Theo quy luật tự nhi&ecirc;n, trung b&igrave;nh một người sẽ mất khoảng 30% tổng lượng collagen khi chạm ngưỡng 40 tuổi.<br />\r\n&nbsp;</p>\r\n\r\n<p>Do đ&oacute;, c&aacute;ch đơn giản v&agrave; kinh tế nhất để giữ m&atilde;i tuổi thanh xu&acirc;n là &nbsp;l&agrave; sử dụng sản ph&acirc;̉m kem dưỡng ch&acirc;́t collagen trắng da Moistone Ostrich Collagen Gel Cung cấp đầy đủ c&aacute;c dưỡng chất cần thiết cho da, gi&uacute;p da giữ ẩm, săn chắc, đ&agrave;n hồi, căng mịn, trắng s&aacute;ng v&agrave; đầy sức sống cũng như l&agrave;m chậm đi qu&aacute; tr&igrave;nh l&atilde;o h&oacute;a da.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Kem dưỡng ch&acirc;́t collagen trắng da Moistone Ostrich Collagen Gel gồm collagen h&ograve;a tan từ đ&agrave; điểu kết hợp với nano collagen từ vi c&aacute; hồng v&agrave; c&aacute;c dưỡng chất qu&yacute; kh&aacute;c được đ&aacute;nh gi&aacute; l&agrave; sản phẩm kem dưỡng da cao cấp tại Nhật Bản, cung cấp đầy đủ c&aacute;c dưỡng chất cần thiết cho da, gi&uacute;p da giữ ẩm, săn chắc, đ&agrave;n hồi, căng mịn, trắng s&aacute;ng v&agrave; đầy sức sống cũng như l&agrave;m chậm đi qu&aacute; tr&igrave;nh l&atilde;o h&oacute;a.</p>\r\n', '2017-11-02 05:12:36', 'Nguyen Anh Tuan'),
(52, 'Kem dưỡng chất collagen trắng da', 'MoistOne1.jpg', '<p><strong>L&agrave;n da rất nhạy cảm với c&aacute;c t&aacute;c động m&ocirc;i trường v&agrave; nhanh ch&oacute;ng &ldquo; xuống cấp&rdquo; nếu kh&ocirc;ng được chăm s&oacute;c cẩn thận.&nbsp;Da th&ocirc; r&aacute;p, nhăn nheo, thiếu sức sống l&agrave; những dấu hiệu l&atilde;o h&oacute;a v&agrave; cũng ch&iacute;nh l&agrave; nỗi &aacute;m ảnh của mọi chị em phụ nữ.</strong></p>\r\n\r\n<p>Ng&agrave;y đăng: 1-11-2017</p>\r\n\r\n<p>576 lượt xem</p>\r\n\r\n<p>Với mong muốn t&igrave;m lại vẻ đẹp đ&ocirc;i mươi, kh&ocirc;ng &iacute;t c&aacute;c chị em đ&atilde; dốc hầu bao đổ v&agrave;o c&aacute;c Spa, thẩm mỹ viện, tiến h&agrave;nh phẫu thuật. Mặc d&ugrave; tốn k&eacute;m v&agrave; mất nhiều thời gian, nhưng chưa chắc đ&atilde; mang lại hiệu quả như &yacute;, thậm tr&iacute; còn làm cho da xấu, gi&agrave; đi trước tuổi.<br />\r\n&nbsp;</p>\r\n\r\n<p>Collagen l&agrave; một loại protein, chiếm 25% tổng lượng protein trong cơ thể, c&oacute; chức năng li&ecirc;n kết c&aacute;c m&ocirc;. Với tổ chức da, b&ecirc;n cạnh nhiệm vụ li&ecirc;n kết, Collagen c&ograve;n c&oacute; chức năng tạo n&ecirc;n sự đ&agrave;n hồi, gi&uacute;p da duy tr&igrave; độ ẩm, tăng khả năng giữ nước để da lu&ocirc;n căng mịn. V&igrave; thế khi collagen bị mất đi do qu&aacute; tr&igrave;nh l&atilde;o ho&aacute; của cơ thể da sẽ bị tr&ugrave;ng nh&atilde;o, nhiều nếp nhăn.Theo quy luật tự nhi&ecirc;n, trung b&igrave;nh một người sẽ mất khoảng 30% tổng lượng collagen khi chạm ngưỡng 40 tuổi.<br />\r\n&nbsp;</p>\r\n\r\n<p>Do đ&oacute;, c&aacute;ch đơn giản v&agrave; kinh tế nhất để giữ m&atilde;i tuổi thanh xu&acirc;n là &nbsp;l&agrave; sử dụng sản ph&acirc;̉m kem dưỡng ch&acirc;́t collagen trắng da Moistone Ostrich Collagen Gel Cung cấp đầy đủ c&aacute;c dưỡng chất cần thiết cho da, gi&uacute;p da giữ ẩm, săn chắc, đ&agrave;n hồi, căng mịn, trắng s&aacute;ng v&agrave; đầy sức sống cũng như l&agrave;m chậm đi qu&aacute; tr&igrave;nh l&atilde;o h&oacute;a da.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Kem dưỡng ch&acirc;́t collagen trắng da Moistone Ostrich Collagen Gel gồm collagen h&ograve;a tan từ đ&agrave; điểu kết hợp với nano collagen từ vi c&aacute; hồng v&agrave; c&aacute;c dưỡng chất qu&yacute; kh&aacute;c được đ&aacute;nh gi&aacute; l&agrave; sản phẩm kem dưỡng da cao cấp tại Nhật Bản, cung cấp đầy đủ c&aacute;c dưỡng chất cần thiết cho da, gi&uacute;p da giữ ẩm, săn chắc, đ&agrave;n hồi, căng mịn, trắng s&aacute;ng v&agrave; đầy sức sống cũng như l&agrave;m chậm đi qu&aacute; tr&igrave;nh l&atilde;o h&oacute;a.</p>\r\n', '2017-11-02 05:12:36', 'Nguyen Anh Tuan'),
(53, 'Kem dưỡng chất collagen trắng da', 'MoistOne1.jpg', '<p><strong>L&agrave;n da rất nhạy cảm với c&aacute;c t&aacute;c động m&ocirc;i trường v&agrave; nhanh ch&oacute;ng &ldquo; xuống cấp&rdquo; nếu kh&ocirc;ng được chăm s&oacute;c cẩn thận.&nbsp;Da th&ocirc; r&aacute;p, nhăn nheo, thiếu sức sống l&agrave; những dấu hiệu l&atilde;o h&oacute;a v&agrave; cũng ch&iacute;nh l&agrave; nỗi &aacute;m ảnh của mọi chị em phụ nữ.</strong></p>\r\n\r\n<p>Ng&agrave;y đăng: 1-11-2017</p>\r\n\r\n<p>576 lượt xem</p>\r\n\r\n<p>Với mong muốn t&igrave;m lại vẻ đẹp đ&ocirc;i mươi, kh&ocirc;ng &iacute;t c&aacute;c chị em đ&atilde; dốc hầu bao đổ v&agrave;o c&aacute;c Spa, thẩm mỹ viện, tiến h&agrave;nh phẫu thuật. Mặc d&ugrave; tốn k&eacute;m v&agrave; mất nhiều thời gian, nhưng chưa chắc đ&atilde; mang lại hiệu quả như &yacute;, thậm tr&iacute; còn làm cho da xấu, gi&agrave; đi trước tuổi.<br />\r\n&nbsp;</p>\r\n\r\n<p>Collagen l&agrave; một loại protein, chiếm 25% tổng lượng protein trong cơ thể, c&oacute; chức năng li&ecirc;n kết c&aacute;c m&ocirc;. Với tổ chức da, b&ecirc;n cạnh nhiệm vụ li&ecirc;n kết, Collagen c&ograve;n c&oacute; chức năng tạo n&ecirc;n sự đ&agrave;n hồi, gi&uacute;p da duy tr&igrave; độ ẩm, tăng khả năng giữ nước để da lu&ocirc;n căng mịn. V&igrave; thế khi collagen bị mất đi do qu&aacute; tr&igrave;nh l&atilde;o ho&aacute; của cơ thể da sẽ bị tr&ugrave;ng nh&atilde;o, nhiều nếp nhăn.Theo quy luật tự nhi&ecirc;n, trung b&igrave;nh một người sẽ mất khoảng 30% tổng lượng collagen khi chạm ngưỡng 40 tuổi.<br />\r\n&nbsp;</p>\r\n\r\n<p>Do đ&oacute;, c&aacute;ch đơn giản v&agrave; kinh tế nhất để giữ m&atilde;i tuổi thanh xu&acirc;n là &nbsp;l&agrave; sử dụng sản ph&acirc;̉m kem dưỡng ch&acirc;́t collagen trắng da Moistone Ostrich Collagen Gel Cung cấp đầy đủ c&aacute;c dưỡng chất cần thiết cho da, gi&uacute;p da giữ ẩm, săn chắc, đ&agrave;n hồi, căng mịn, trắng s&aacute;ng v&agrave; đầy sức sống cũng như l&agrave;m chậm đi qu&aacute; tr&igrave;nh l&atilde;o h&oacute;a da.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Kem dưỡng ch&acirc;́t collagen trắng da Moistone Ostrich Collagen Gel gồm collagen h&ograve;a tan từ đ&agrave; điểu kết hợp với nano collagen từ vi c&aacute; hồng v&agrave; c&aacute;c dưỡng chất qu&yacute; kh&aacute;c được đ&aacute;nh gi&aacute; l&agrave; sản phẩm kem dưỡng da cao cấp tại Nhật Bản, cung cấp đầy đủ c&aacute;c dưỡng chất cần thiết cho da, gi&uacute;p da giữ ẩm, săn chắc, đ&agrave;n hồi, căng mịn, trắng s&aacute;ng v&agrave; đầy sức sống cũng như l&agrave;m chậm đi qu&aacute; tr&igrave;nh l&atilde;o h&oacute;a.</p>\r\n', '2017-11-02 05:12:36', 'Nguyen Anh Tuan'),
(54, 'Kem dưỡng chất collagen trắng da', 'MoistOne1.jpg', '<p><strong>L&agrave;n da rất nhạy cảm với c&aacute;c t&aacute;c động m&ocirc;i trường v&agrave; nhanh ch&oacute;ng &ldquo; xuống cấp&rdquo; nếu kh&ocirc;ng được chăm s&oacute;c cẩn thận.&nbsp;Da th&ocirc; r&aacute;p, nhăn nheo, thiếu sức sống l&agrave; những dấu hiệu l&atilde;o h&oacute;a v&agrave; cũng ch&iacute;nh l&agrave; nỗi &aacute;m ảnh của mọi chị em phụ nữ.</strong></p>\r\n\r\n<p>Ng&agrave;y đăng: 1-11-2017</p>\r\n\r\n<p>576 lượt xem</p>\r\n\r\n<p>Với mong muốn t&igrave;m lại vẻ đẹp đ&ocirc;i mươi, kh&ocirc;ng &iacute;t c&aacute;c chị em đ&atilde; dốc hầu bao đổ v&agrave;o c&aacute;c Spa, thẩm mỹ viện, tiến h&agrave;nh phẫu thuật. Mặc d&ugrave; tốn k&eacute;m v&agrave; mất nhiều thời gian, nhưng chưa chắc đ&atilde; mang lại hiệu quả như &yacute;, thậm tr&iacute; còn làm cho da xấu, gi&agrave; đi trước tuổi.<br />\r\n&nbsp;</p>\r\n\r\n<p>Collagen l&agrave; một loại protein, chiếm 25% tổng lượng protein trong cơ thể, c&oacute; chức năng li&ecirc;n kết c&aacute;c m&ocirc;. Với tổ chức da, b&ecirc;n cạnh nhiệm vụ li&ecirc;n kết, Collagen c&ograve;n c&oacute; chức năng tạo n&ecirc;n sự đ&agrave;n hồi, gi&uacute;p da duy tr&igrave; độ ẩm, tăng khả năng giữ nước để da lu&ocirc;n căng mịn. V&igrave; thế khi collagen bị mất đi do qu&aacute; tr&igrave;nh l&atilde;o ho&aacute; của cơ thể da sẽ bị tr&ugrave;ng nh&atilde;o, nhiều nếp nhăn.Theo quy luật tự nhi&ecirc;n, trung b&igrave;nh một người sẽ mất khoảng 30% tổng lượng collagen khi chạm ngưỡng 40 tuổi.<br />\r\n&nbsp;</p>\r\n\r\n<p>Do đ&oacute;, c&aacute;ch đơn giản v&agrave; kinh tế nhất để giữ m&atilde;i tuổi thanh xu&acirc;n là &nbsp;l&agrave; sử dụng sản ph&acirc;̉m kem dưỡng ch&acirc;́t collagen trắng da Moistone Ostrich Collagen Gel Cung cấp đầy đủ c&aacute;c dưỡng chất cần thiết cho da, gi&uacute;p da giữ ẩm, săn chắc, đ&agrave;n hồi, căng mịn, trắng s&aacute;ng v&agrave; đầy sức sống cũng như l&agrave;m chậm đi qu&aacute; tr&igrave;nh l&atilde;o h&oacute;a da.</p>\r\n\r\n<p>&nbsp;</p>\r\n\r\n<p>Kem dưỡng ch&acirc;́t collagen trắng da Moistone Ostrich Collagen Gel gồm collagen h&ograve;a tan từ đ&agrave; điểu kết hợp với nano collagen từ vi c&aacute; hồng v&agrave; c&aacute;c dưỡng chất qu&yacute; kh&aacute;c được đ&aacute;nh gi&aacute; l&agrave; sản phẩm kem dưỡng da cao cấp tại Nhật Bản, cung cấp đầy đủ c&aacute;c dưỡng chất cần thiết cho da, gi&uacute;p da giữ ẩm, săn chắc, đ&agrave;n hồi, căng mịn, trắng s&aacute;ng v&agrave; đầy sức sống cũng như l&agrave;m chậm đi qu&aacute; tr&igrave;nh l&atilde;o h&oacute;a.</p>\r\n', '2017-11-02 05:12:36', 'Nguyen Anh Tuan');

--
-- Chỉ mục cho các bảng đã đổ
--

--
-- Chỉ mục cho bảng `tb_tintuc`
--
ALTER TABLE `tb_tintuc`
  ADD PRIMARY KEY (`id_tintuc`);

--
-- AUTO_INCREMENT cho các bảng đã đổ
--

--
-- AUTO_INCREMENT cho bảng `tb_tintuc`
--
ALTER TABLE `tb_tintuc`
  MODIFY `id_tintuc` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=55;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
